name: Deploy
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create config file
        run: |
          echo "const config = {
            SUPABASE_URL: '${{ secrets.SUPABASE_URL }}',
            SUPABASE_KEY: '${{ secrets.SUPABASE_KEY }}',
            MORPHCAST_LICENSE: '${{ secrets.MORPHCAST_LICENSE }}',
            COMPLETION_CODE: '${{ secrets.COMPLETION_CODE }}',
            TASK_ID: '${{ secrets.TASK_ID }}'
          }; export default config;" > config.js

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
